version: '3.9'

services:
  db:
    build:
      context: ./src/
      dockerfile: Dockerfile
    container_name: db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
