version: '3.9'

services:
  db:
    build:
      context: ./src
    container_name: db
    ports:
      - 5431:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
